Traceback (most recent call last):
  File "C:\Users\M2S\Desktop\Workspace\PythonWorkspace\automate_boring_stuff\ch11_debugging\02_getting_traceback_as_string.py", line 14, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
